name: Deploy to Multi-Tenant (store.zaviago.com)

on:
  push:
    branches:
      - feat/multi-tanent

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_LINE_CLIENT_ID: ${{ vars.MULTI_TENANT_VITE_LINE_CLIENT_ID }}
      VITE_ADMIN_URL: ${{ vars.MULTI_TENANT_VITE_ADMIN_URL }}
      VITE_CALLBACK_DOMAIN: ${{ vars.MULTI_TENANT_VITE_CALLBACK_DOMAIN }}
      VITE_SUPABASE_URL: ${{ vars.MULTI_TENANT_VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ vars.MULTI_TENANT_VITE_SUPABASE_ANON_KEY }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env.compose file
        run: |
          echo "VITE_LINE_CLIENT_ID=$VITE_LINE_CLIENT_ID" >> .env.compose
          echo "VITE_ADMIN_URL=$VITE_ADMIN_URL" >> .env.compose
          echo "VITE_CALLBACK_DOMAIN=$VITE_CALLBACK_DOMAIN" >> .env.compose
          echo "VITE_SUPABASE_URL=$VITE_SUPABASE_URL" >> .env.compose
          echo "VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY" >> .env.compose

      - name: Copy .env.compose to Multi-Tenant Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.MULTI_TENANT_SSH_HOST }}
          username: ${{ vars.MULTI_TENANT_SSH_USERNAME }}
          key: ${{ secrets.MULTI_TENANT_SSH_PRIVATE_KEY }}
          port: ${{ vars.MULTI_TENANT_SSH_PORT }}
          source: .env.compose
          target: /root/glowfish-web
          overwrite: true
          timeout: 600

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.MULTI_TENANT_SSH_HOST }}
          username: ${{ vars.MULTI_TENANT_SSH_USERNAME }}
          key: ${{ secrets.MULTI_TENANT_SSH_PRIVATE_KEY }}
          port: ${{ vars.MULTI_TENANT_SSH_PORT }}
          script: |
            cd /root/glowfish-web
            git pull
            docker-compose down
            docker-compose --env-file .env.compose build
            docker-compose --env-file .env.compose up -d 