name: Deploy to Multi-Tenant (stg-store.zaviago.com)

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ vars.STAGE_MULTI_TENANT_SUPABASE_PROJECT_ID }}
      VITE_LINE_CLIENT_ID: ${{ vars.STAGE_MULTI_TENANT_VITE_LINE_CLIENT_ID }}
      VITE_LINE_CLIENT_SECRET: ${{ secrets.STAGE_MULTI_TENANT_VITE_LINE_CLIENT_SECRET }}
      VITE_SUPABASE_URL: ${{ vars.STAGE_MULTI_TENANT_VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ vars.STAGE_MULTI_TENANT_VITE_SUPABASE_ANON_KEY }}
      VITE_SERVICE_ROLE_KEY: ${{ secrets.STAGE_MULTI_TENANT_VITE_SERVICE_ROLE_KEY }}
      SMS2PRO_API: ${{ secrets.SMS2PRO_API }}
      STORAGE_BUCKET: ${{ vars.STORAGE_BUCKET }}
      VITE_ADMIN_URL: ${{ vars.STAGE_MULTI_TENANT_VITE_ADMIN_URL }}
      VITE_CALLBACK_DOMAIN: ${{ vars.STAGE_MULTI_TENANT_VITE_CALLBACK_DOMAIN }}
      VITE_PUBLIC_POSTHOG_HOST: ${{ vars.STAGE_MULTI_TENANT_VITE_PUBLIC_POSTHOG_HOST }}
      VITE_PUBLIC_POSTHOG_KEY: ${{ vars.STAGE_MULTI_TENANT_VITE_PUBLIC_POSTHOG_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: create .env file
        run: |
          echo "VITE_LINE_CLIENT_ID=$VITE_LINE_CLIENT_ID" >> ./supabase/.env
          echo "VITE_LINE_CLIENT_SECRET=$VITE_LINE_CLIENT_SECRET" >> ./supabase/.env
          echo "VITE_SUPABASE_URL=$VITE_SUPABASE_URL" >> ./supabase/.env
          echo "VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY" >> ./supabase/.env
          echo "VITE_SERVICE_ROLE_KEY=$VITE_SERVICE_ROLE_KEY" >> ./supabase/.env
          echo "SMS2PRO_API=$SMS2PRO_API" >> ./supabase/.env
          echo "VITE_ADMIN_URL=$VITE_ADMIN_URL" >> ./supabase/.env
          echo "VITE_DEFAULT_STORE=$VITE_DEFAULT_STORE" >> ./supabase/.env
          echo "STORAGE_BUCKET=$STORAGE_BUCKET" >> ./supabase/.env
          echo "VITE_PUBLIC_POSTHOG_HOST=$VITE_PUBLIC_POSTHOG_HOST" >> ./supabase/.env
          echo "VITE_PUBLIC_POSTHOG_KEY=$VITE_PUBLIC_POSTHOG_KEY" >> ./supabase/.env

      - name: update supabase functions and secret
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase secrets set --env-file ./supabase/.env
          supabase functions deploy

      - name: Create .env.compose file
        run: |
          echo "VITE_LINE_CLIENT_ID=$VITE_LINE_CLIENT_ID" >> .env.compose
          echo "VITE_ADMIN_URL=$VITE_ADMIN_URL" >> .env.compose
          echo "VITE_CALLBACK_DOMAIN=$VITE_CALLBACK_DOMAIN" >> .env.compose
          echo "VITE_SUPABASE_URL=$VITE_SUPABASE_URL" >> .env.compose
          echo "VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY" >> .env.compose

      - name: Copy .env.compose to Multi-Tenant Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.STAGE_MULTI_TENANT_SSH_HOST }}
          username: ${{ vars.STAGE_MULTI_TENANT_SSH_USERNAME }}
          key: ${{ secrets.STAGE_MULTI_TENANT_SSH_PRIVATE_KEY }}
          port: ${{ vars.STAGE_MULTI_TENANT_SSH_PORT }}
          source: .env.compose
          target: /root/glowfish-web
          overwrite: true
          timeout: 600s

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.STAGE_MULTI_TENANT_SSH_HOST }}
          username: ${{ vars.STAGE_MULTI_TENANT_SSH_USERNAME }}
          key: ${{ secrets.STAGE_MULTI_TENANT_SSH_PRIVATE_KEY }}
          port: ${{ vars.STAGE_MULTI_TENANT_SSH_PORT }}
          script: |
            cd /root/glowfish-web
            git fetch --all
            git reset --hard origin/staging
            ./.github/scripts/update_caddyfile.sh ${{ vars.STAGE_MULTI_TENANT_VITE_CALLBACK_DOMAIN }}
            docker-compose down
            docker-compose --env-file .env.compose build
            docker-compose --env-file .env.compose up -d 